name: PR Validation

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches: [ "main" ]

jobs:
  test:
    name: Test and Build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Run tests
      run: mvn clean test

    - name: Build project
      run: mvn -B package --file pom.xml

    - name: Test Summary
      if: always()
      run: |
        echo "### Test Results" >> $GITHUB_STEP_SUMMARY
        echo "All tests passed successfully" >> $GITHUB_STEP_SUMMARY
